import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import { createFsdBoundariesConfig } from "@simpleinvoice/config/eslint-base.mjs";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // FSD layer import boundary enforcement
  createFsdBoundariesConfig(),
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // shadcn/ui — auto-generated by CLI, treat as vendor code
    "src/shadcn/**",
  ]),
]);

export default eslintConfig;
